#include <stdio.h>

int main() {
    printf("\033[0;30m""\nINTODUCTION TO C\n"
           "C is a very powerful and flexible general purpose language that has\n"
           "gained world wide acceptance over the year,c has its origin in the early\n"
           "1970s in Basic Combined Programming language,a project shared by AT&T Bell labs,USA,\n "
           "and developed by Martin Richard\n"
           "\033[0m"
           "\033[1;30m"
           "\nc is widey accepted for its performance ,portability ,versatility ,simplicity and modularity\n"
           "\033[0m"
           "\033[0;31m"
           "\n\nC CHARACTER SET\n"
           "\033[0m"
           "As a launguage c is a set of character that the c programming language recognizes.\nIt includes:"
           "\033[1;31m"
           "\n all (small and capital) alphabets \nnumeric digits\nspecial charcters(/*-+!@#%^&*()_?:~)etc\n"
           "\033[0m"
           "\033[0;33m"
           "\n\nC KEYWORDS :\nc keyword are reserved which are for any special purpose.\nin c their is 32 keywords\n"
           "\033[0m"
           "\033[1;33m"
           "examples:\nauto ,static ,register ,extern,typedef,void,char,long,int,short,\nfloat,double,signed,unsigned,"
           "const,volatile,enum,\nstruct,union,if,else,for,while,do,switch,case,default,continue,break,goto,return,sizeof"
           "\033[0m"
           "\033[0;34m"
           "\n\nWHITESPACE IN C:\nany combination of spaces,tab or newline is called whitespace in c.\n"
           "c is a free form language so the c compiler recognizes the whitespace and ignore it "
           "\033[1;34m""\n\nDATATYPE IN C:\nc has usual simple datatypes:\ncharacter,integer,fractional values\n"
           "that is char,int,float,double(represents double precision in the float values \n"
           "their are some type modifier to increase the capability of the modifiers\n"
           "1. SHORT:\nthe length of the short variable is at least 16 bits\n only used with the int datatype.\n "
           "2. LONG:\nthe length of the long variable is at least 32 bits\n only used with the int datatype."
           "\n3. SIGNED:\nsigned numbers are positive ,negative,or zero.\n used with char and int both with or without short and long modifiers"
           "\n4. UNSIGNED:\nunsigned numbers are only positive""\033[0m"
           "\033[0;35m""\n\n CONSTANTS IN C\n"
           "as from its name constants are those values which don't change\n"
           "constants in c are stored in memory locations.In c constants are divided in two categories:\n"
           "\n1. PRIMARY CONSTANTS:"
           "\na. INTEGER CONSTANTS:\nincludes one or more digits without any point"
           "\nb. REAL CONSTANTS:\n>*. fractional form:\none or more digits with any point and with a preceding +ve or -ve sign or no sign"
           "\n>*. EXPONENTIAL CONSTANTS:\nin this we represent the real constant in two parts\n"
           "exponent and mantissa,separated by 'e'"
           "\nc. CHARACTER CONSTANT:\nit is a single alphanumeric or a single symbol enclosed with in single quotes"
           "\n\n2. SECONDARY CONSTANTS:\nstring consatnts'etc;"
           "\033[0m"
           "\033[1;35m""\n\nSTRING CONSTANT:\n a sequence of charcaters enclosed within double quotes is a string."
           "note the the character and string are of differnt types as abided by in c."
           "\033[0m"
           "\033[1;35m"
           "\n\n VARIABLES IN C:\na variable is a quantity that can be change."
           "every variable has its own datatype(also called domain)"
           "\n a variable is any combination of alphanumerics and underscores where"
           "the first character is an alphabet \nor an underscore"
           "no whitespaces are not allowed within \nthe variable name"
           "upper case and lower case  letters are distinct"
           "\033[0m"
           "\033[0;36m""\n\nFUNCTION IN C:\n"
           "the c is based on the concept of the bulding blocks."
           "the building blocks are called functions"
           "\nA c program is a collection of one or more functions"
           "every c program has a main function"
           "\033[0m"
           "\033[1;36m""\n\nUSEFUL IDENTIFIER NAMING CONVENTIONS\n" "\033[0m"
           "\033[0;37m"
           "SOME BASIC AND USEFUL VARIABLE AND NAMING TECHNIQUES ARE LISTED BELOW "
           "\n 1. try using a meaningful a name is possible"
           "\n 2. avoid full words in a variable names if the name become too large "
           "(even if the compiler support to write long variable because it becomes a \npain to write long variable names"
           "\n 3. the trick is to balance the length of the variable names by using "
           "such a name which can express the content impressively"
           "\n 4. use of underscore (_)"
           "\033[0m"
           "\033[1;37""\n\nTYPE _ DECLARATION VARIABLES\n"
           "statements and instruction are the program units contained in functions"
           "\n these statements define and declare the variables for their use in function and their types"
           "DATATYPE VARIABLE_IDENTIFIER {,VARIABLE_IDENTIFIER;""\033[0m"
           "\033[0;37m""\n\nOPERATORS"
           "\n the c language is rich in operators.An operator is a symbol that instructs the compiler to perform "
           "specific manipulation:\n_arithmetic,_logical or otherwise c has three general classes of operators "
           ",viz,arithmetic,relational,and logical,and bitwise"
           "\nexample\na=b+c""\033[0m"
           "\033[1;37m""\n\n1. ARITHMETIC OPERATORS:\nc provides the common binary arithmetic operators of addition"
           "(+),subtaction(-),multiplication(*),and division(/).\n in addition c also provides the unary minnus(-)"
           "operator\n the precedence of all the operators are as below"
           "\n() > -(unary) > *,/ > +,- (highest to lowest)""\033[0m"
           "\033[0;38m" "\n\n2. ASSIGNMENT OPERATOR:\n the assignment operator in C is '='.\n it is a binary operator used to assign"
           "value to the variables. \n general form of this operator:\n"
           "LValue = RValue;""\033[0m"
           "\033[1;38m""\n\n3. INCREMENT AND DECREMENT OPERATOR""\nfor increment (++) and for decrement (--) operator are used"
           "\nexample\n++test (prefix form.> it first increment by 1 the value of test the use the test)"
           "\ntest-- (postfix form.> it first use the value of test then increment it with 1""\033[0m"
           "\033[0;39m""\n\nMODULUS DIVISION OPERATOR\nthe operator'%' is the modulo division operator in C"
           ".It can be used  \nonly to integer types such as int and long,with or without type qualifiers "
           "EXAMPLE\nX=4;\nZ=X% 2;"
           "\033[0m"
           "\033[1;39m""\n\nSHORTHAND OPERATORS\nc providesa number of shorthand operators,which combines "
           "the tasks of carrying out arithmetic operations as well as assignment."
           "\n this operator includes:>"
           "\n += , -= , *= , /= ,%=  \n"
           """\033[0m"
           "\033[0;40m""\n\nRELATIONAL AND LOGICAL OPERATORS"
           "\n the relational operators'=='(equal to),'!='(not equal to), '<' less than , '<=' less than or \nequal to),"
           "'>'(greater than), and '>='(greater than or equal to) are all binary.\nThe equality operatoris indicated by '=='"
           "to avoid confusion from the assignment operator '='."
           "\n all relational operator take two expressions as operands and yield either the value zero or a \nnon zero once"
           "\nEXAMPLE\nA<5\nP-99==57*Q,....ETC ""\033[0m"
           "\033[1;40m""\n\nBITWISE OPERATORS\n"
           "C provides low level mechanisms to manipulate data at the level of individual bits\n\n"
           "\033[0m""\033[1;40m""\n bit is a single BInary digiT - a zero '0' or a on'1' \n""\033[0m"
           "\033[0;41m""\033[0;30m""\nBITWISE AND , OR , XOR , << (shift left) , >> (shift right), ~ (one's complement):\nC"
           "provides six operators for bit manipulation of integral data types."
           "\033[0m""\033[1;41m""\033[1;30m" "\n\nTERNARY CONDITIONAL OPERATORS"
           "C includes a very special types of operator called the ternary conditional operator.\nits basic syntax is:\n"
           "EXPRESSION1 ? EXPRESSION2 : EXPRESSION3;\n\n""\033[0m"
           "\033[1;41m""\033[1;30m""SIZEOF OPERATOR :\n C provides the unary operator sizeof to find the number of bytes needed to store"
           "\nan object . It has the same precedence and associativity as the other unary \noperators of the form"
           "\nsizeof(object) is an integer that represents the number of bytes needed to \nsolve to store the object in memory\n\n"
           "\033[0m"
           "\033[0;42m""\033[1;30m""TYPE CASTING :\n the type of an expression can also be converted explicitly by\n"
           "type casting.the general form of a type cast is "
           "\n (Data Type) Expression\n"
           "int a =8;"
           "\nfloat p=5;"
           "\n...."
           "\np= (float)(a)/p;\n\n"
           "\033[0m"
           "\033[0;43m""\033[1;30m""COMMENTS:"
           "\ncomments are written in C to enhance the readability of the program.\ncomments "
           "may be written to indicate the platform on which the program is written to run on,"
           "\n the author of the program ,the purpose of the program ,the purpose"
           "\n of a statement ,or any other documentation purpose."
           "\n\n comments are of two types:"
           "MULTI LINE COMMENT:"
           "\n/* and ends with */ \n"
           "SINGLE LINE COMMENTS :\n "
           "starts with double backslash "
           " and no need to close\n\n""\033[0m"
           "\033[1;44m""\033[1;30m""FUNCTION REVISITED:"
           "\n a function in C are named so that they canbe referenced \nusing the name of the function "
           "It must not coincide with a variable name or a reversed keyword"
           "\nReturnType FunctionName  (Argument List)"
           "  {\n (Body of the function) \n Definations and Declarations;\n statements;\n}\n\n""\033[0m"
           "\033[1;45m""\033[1;30m""AT LAST SOME MAIN EXTRA POINTS :"
           "\n c code is made readable by introducing commentd\n"
           "as and when required. the c compiler  ignores comments .To\n"
           "facilitate i/o ,C provides formatted and unformatted i/o functions.\n"
           "the scanf() is a standard input function declared in stdio.h.\n\n ""\033[0m"
           "\033[1;46m""\033[1;30m""the rules of the scope and visibility determine the acess to variables \n"
           "ina program .acoording ,there may be local and global variables. \n"
           "compound statements are a group of statements logically grouped together\n\n""\033[0m"
           "\033[1;47m""\033[1;30m""the storage class of a variable further determines the rules of scope\n"
           ",visibility and storage. there are four storage classes-:"
           "\n AUTOMATIC ,REGISTER ,STATIC and EXTERNAL.\n  "
           "\033[0m"
           "TO BE CONTINUED...............");

    return 0;
}